version: '2'
services:
  flaskapp:
    build: .
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    env_file:
      - env_file
    volumes:
      - .:/opt/services/flaskapp/src
    networks:
      - web_nw
  nginx:
    image: "nginx:1.13.5"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on: 
      - flaskapp
networks:
  web_nw:
    driver: bridge
volumes:
  dbdata:
